### PR TITLE
DRAFT: Add ayatana to debian control

### PR DESCRIPTION
**Pull request by LyzardKing**
Switch to Ayatana AppIndicators by default, and fall back to appindicators if not found.
Ubuntu-mate now uses ayatana indicators by default

https://lists.debian.org/debian-devel/2018/03/msg00506.html

### CODE REVIEW

**Comment by LyzardKing** [comment]
This still needs testing, there are debian patches to blueman that need to be ported.
The patch file can be found in the debian folder at https://packages.debian.org/bookworm/blueman

In debian the patch is applied from bullseye (stable) forward

**Comment by souravdas142** [comment]
Sorry @LyzardKing  will be looking into this tonight.

**Review by souravdas142 — COMMENTED** [review]
below ubuntu 21.10, `appindicator` is used only, not `ayatana` so when this patch is applied with that `debian/patch` all package from ubuntu 18.04 to now will be set default to ayatana right ? If some ubuntu version (below 21.10) by default use `appindicator` they also use `ayatana` bydefault then (by downloading that package). 

to remove this behaviour we also can do 
```bash
gir1.2-ayatanaappindicator3-0.1 (>= 0.5.5) | gir1.2-appindicator3-0.1,
```
0.5.5 include only in impish and later version of ubuntu... 

but how to include `debian/patch/ayatana.patch` conditionally ? any idea ?
Conditionally means, I was thinking to check ubuntu version, if ubuntu version is >20.04, then only this patch get applied.
otherwise if still `ayatana` package is not found the patch gets applied right ?

Or, 

If I just apply this patch globally is there any conflicts happen with `appindicator` and `ayatana` ?

**Comment by LyzardKing** [comment]
the debian/control file does not need the version, since one of the two will be installed anyway.
Regarding the patch, I tried uploading a possible conditional inclusion.
I haven't tested it yet, but I can try building either later today or tomorrow.
Basically if the ayatana libs are installed it uses that, if not it falls back to appindicator

**Comment by souravdas142** [comment]
@LyzardKing  ecdbce0c485a84683e7275815b23c4c46df7370c fixes patch is not getting applied and add entry in `debian/patches/series` file
rest of commit just reworded commit messages 
also rebased on current `development` branch
Can you please recheck whether everything is ok ?  can we merge it now ?

**Comment by LyzardKing** [comment]
The patch should be applied correctly now I believe.
There should be nothing else to change

**Pull request merged**
